In [58]:
import pandas as pd

In [59]:
air_quality = pd.read_csv("data/air_quality_no2.csv", index_col=0, parse_dates=True)

In [60]:
air_quality.head()

                     station_antwerp  station_paris  station_london
datetime
2019-05-07 02:00:00              NaN            NaN            23.0
2019-05-07 03:00:00             50.5           25.0            19.0
2019-05-07 04:00:00             45.0           27.7            19.0
2019-05-07 05:00:00              NaN           50.4            16.0
2019-05-07 06:00:00              NaN           61.9             NaN

In [61]:
air_quality["london_mg_per_cubic"] = air_quality["station_london"] * 1.882

In [62]:
air_quality.head()

,station_antwerp,station_paris,station_london,london_mg_per_cubic
datetime,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,43.286
2019-05-07 03:00:00,50.5,25.0,19.0,35.758
2019-05-07 04:00:00,45.0,27.7,19.0,35.758
2019-05-07 05:00:00,NaN,50.4,16.0,30.112
2019-05-07 06:00:00,NaN,61.9,NaN,NaN

In [63]:
air_quality["london_mg_per_cubic"] = air_quality["station_london"] + 5

In [64]:
air_quality.head()

,station_antwerp,station_paris,station_london,london_mg_per_cubic
datetime,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,28.0
2019-05-07 03:00:00,50.5,25.0,19.0,24.0
2019-05-07 04:00:00,45.0,27.7,19.0,24.0
2019-05-07 05:00:00,NaN,50.4,16.0,21.0
2019-05-07 06:00:00,NaN,61.9,NaN,NaN

In [65]:
air_quality["ratio_paris_antwerp"] = (
    air_quality["station_paris"] / air_quality["station_antwerp"]
)

In [66]:
air_quality.head()

,station_antwerp,station_paris,station_london,london_mg_per_cubic,ratio_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,28.0,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,24.0,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,24.0,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,21.0,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [67]:
air_quality_renamed = air_quality.rename(
    columns={
        "station_antwerp": "BETR801",
        "station_paris": "FR04014",
        "station_london": "London Westminster",
    }
)

In [68]:
air_quality_renamed.head()

,BETR801,FR04014,London Westminster,london_mg_per_cubic,ratio_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,28.0,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,24.0,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,24.0,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,21.0,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [69]:
air_quality_renamed = air_quality_renamed.rename(columns=str.upper)
air_quality_renamed.head()

,BETR801,FR04014,LONDON WESTMINSTER,LONDON_MG_PER_CUBIC,RATIO_PARIS_ANTWERP
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,28.0,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,24.0,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,24.0,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,21.0,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [70]:
air_quality_renamed = air_quality_renamed.rename(columns=str.lower)
air_quality_renamed.head()

,betr801,fr04014,london westminster,london_mg_per_cubic,ratio_paris_antwerp
datetime,,,,,
2019-05-07 02:00:00,NaN,NaN,23.0,28.0,NaN
2019-05-07 03:00:00,50.5,25.0,19.0,24.0,0.495050
2019-05-07 04:00:00,45.0,27.7,19.0,24.0,0.615556
2019-05-07 05:00:00,NaN,50.4,16.0,21.0,NaN
2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [71]:
titanic = pd.read_csv("data/titanic.csv")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [72]:
titanic["Age"].mean()

np.float64(29.69911764705882)

In [73]:
titanic["Fare"].mean()

np.float64(32.204207968574636)

In [74]:
titanic["Pclass"].mean()

np.float64(2.308641975308642)

In [75]:
titanic[["Age", "Fare"]].median()

Age     28.0000
Fare    14.4542
dtype: float64

In [76]:
titanic["Age"].median()

28.0

In [77]:
titanic[["Age", "Fare"]].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [78]:
titanic.agg(
    {
        "Age": ["min", "max", "median", "skew"],
        "Fare": ["min", "max", "median", "mean"],
    }
)

              Age        Fare
min      0.420000    0.000000
max     80.000000  512.329200
median  28.000000   14.454200
skew     0.389108         NaN
mean          NaN   32.204208

In [79]:
titanic[["Sex", "Age"]].groupby("Sex").mean()

              Age
Sex
female  27.915709
male    30.726645

In [80]:
titanic.groupby("Sex").mean(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
female,431.028662,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818
male,454.147314,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893

In [81]:
titanic.groupby("Sex")["Age"].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [82]:
titanic.groupby(["Sex", "Pclass"])["Fare"].mean()

Sex     Pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: Fare, dtype: float64

In [83]:
titanic["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [84]:
titanic.groupby("Pclass")["Pclass"].count()

Pclass
1    216
2    184
3    491
Name: Pclass, dtype: int64

In [85]:
titanic.sort_values(by="Age").head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [86]:
titanic.sort_values(by=['Pclass', 'Age'], ascending=False).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S

In [87]:
no2 = air_quality[air_quality["parameter"] == "no2"]

KeyError: 'parameter'